### ISSUE TITLE
Invalid Json

### ISSUE THREAD

**Issue by Frost199** [tomiwaajayi/HNGi7-task-2#322]
The JSON format is invalid and doesn't support the RFC 8259 standard

**Comment by sudo-kaizen** [comment]
@Frost199 Can you please give a sample of the expected output and the actual output you are receiving?

**Comment by Frost199** [comment]
![Screenshot from 2020-06-04 11-35-31](https://user-images.githubusercontent.com/25561713/83747498-9ed03700-a658-11ea-8d9a-812225a7922a.png)

@sudo-kaizen here you go
